services:
  postgres:
    image: library/postgres:13
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=test psql -U program -d persons -c 'SELECT 1' >/dev/null"]
      interval: 2s
      timeout: 3s
      retries: 15
      start_period: 5s

volumes:
  db-data:
